export type TaxSystem =
  | "GENERAL_TAX_SYSTEM"
  | "SIMPLIFIED_TAX_SYSTEM_INCOME"
  | "SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME"
  | "UNIFIED_AGRICULTURAL_TAX"
  | "PRESUMPTIVE_TAX_SYSTEM"
  | "PATENT_BASED"
